import { Link } from 'react-router-dom'
import Navigation from './Navigation'
import './CommandsPage.css'

interface Command {
    name: string
    description: string
    category: string
}

const commands: Command[] = [
    {
        name: 'commit',
        description: 'Generate intelligent commit messages using AI analysis of your code changes',
        category: 'Core Git Commands'
    },
    {
        name: 'audio-commit',
        description: 'Record audio to provide context for commit message generation using speech-to-text',
        category: 'Audio Commands'
    },
    {
        name: 'review',
        description: 'Generate comprehensive reviews and create GitHub issues from your feedback',
        category: 'Review & Issues'
    },
    {
        name: 'audio-review',
        description: 'Record audio feedback that gets transcribed and converted into actionable GitHub issues',
        category: 'Audio Commands'
    },
    {
        name: 'release',
        description: 'Generate comprehensive release notes from git history and changes',
        category: 'Release Management'
    },
    {
        name: 'publish',
        description: 'Automate package publishing with version management and dependency updates',
        category: 'Publishing'
    },
    {
        name: 'tree',
        description: 'Analyze dependency order and execute commands across multiple packages in a workspace',
        category: 'Workspace Management'
    },
    {
        name: 'link',
        description: 'Link workspace packages for local development by updating package.json dependencies',
        category: 'Workspace Management'
    },
    {
        name: 'unlink',
        description: 'Restore original package.json dependencies for production deployment',
        category: 'Workspace Management'
    },
    {
        name: 'select-audio',
        description: 'Configure and test your microphone device for audio commands',
        category: 'Configuration'
    },
    {
        name: 'clean',
        description: 'Remove output directory and temporary files generated by KodrDriv',
        category: 'Utility'
    }
]

const categories = Array.from(new Set(commands.map(cmd => cmd.category)))

function CommandsPage() {
    return (
        <div className="documentation-layout">
            <header className="doc-header">
                                    <div className="doc-header-content">
                        <div className="logo-section">
                            <a href="/kodrdriv/" className="logo-link">
                                <img
                                    src="/kodrdriv/kodrdriv-logo.svg"
                                    alt="KodrDriv Logo"
                                    width="40"
                                    height="40"
                                    className="doc-logo"
                                />
                                <h1>KodrDriv</h1>
                            </a>
                        </div>
                    <div className="header-links">
                        <a href="https://github.com/grunnverk/kodrdriv" target="_blank" rel="noopener noreferrer">
                            GitHub
                        </a>
                        <a href="https://www.npmjs.com/package/@grunnverk/kodrdriv" target="_blank" rel="noopener noreferrer">
                            NPM
                        </a>
                    </div>
                </div>
            </header>
            <Navigation />
            <main className="doc-main">
                <div className="doc-container">
                    <div className="commands-page">
                        <div className="commands-header">
                            <h1>Commands</h1>
                            <p className="commands-description">
                                KodrDriv provides comprehensive commands for automating Git workflows,
                                generating intelligent documentation, and managing audio-driven development workflows.
                            </p>
                        </div>

                        <div className="commands-grid">
                            {categories.map(category => (
                                <div key={category} className="command-category">
                                    <h3 className="category-title">{category}</h3>
                                    <div className="category-commands">
                                        {commands
                                            .filter(cmd => cmd.category === category)
                                            .map(command => (
                                                <Link
                                                    key={command.name}
                                                    to={`/commands/${command.name}`}
                                                    className="command-card"
                                                >
                                                    <div className="command-header">
                                                        <h4 className="command-name">
                                                            <code>{command.name}</code>
                                                        </h4>
                                                    </div>
                                                    <p className="command-description">
                                                        {command.description}
                                                    </p>
                                                    <div className="command-footer">
                                                        <span className="view-docs">View Documentation →</span>
                                                    </div>
                                                </Link>
                                            ))
                                        }
                                    </div>
                                </div>
                            ))}
                        </div>

                        <div className="commands-quick-start">
                            <h2>Quick Start</h2>
                            <div className="quick-start-content">
                                <div className="quick-start-step">
                                    <h3>1. Configuration</h3>
                                    <p>Before using KodrDriv commands, set up your configuration:</p>
                                    <pre><code>kodrdriv --init-config</code></pre>
                                </div>
                                <div className="quick-start-step">
                                    <h3>2. First Commit</h3>
                                    <p>Generate your first AI-powered commit message:</p>
                                    <pre><code>kodrdriv commit</code></pre>
                                </div>
                                <div className="quick-start-step">
                                    <h3>3. Audio Setup (Optional)</h3>
                                    <p>Configure your microphone for audio commands:</p>
                                    <pre><code>kodrdriv select-audio</code></pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer className="doc-footer">
                <div className="container">
                    <p>
                        Built with ❤️ by{' '}
                        <a href="https://github.com/grunnverk" target="_blank" rel="noopener noreferrer">
                            Tim O'Brien
                        </a>
                    </p>
                    <p className="license">Licensed under Apache-2.0</p>
                </div>
            </footer>
        </div>
    )
}

export default CommandsPage
